### ISSUE TITLE
Same `group` name across multiple maps causes LayerControl() to stop working correctly.

### ISSUE THREAD

**Issue by ajjitn** [tomroh/leaflegend#91] opened 2024-11-27 16:03 UTC
I believe this is a duplicate of closed issue #78, but just wanted to attach a reprex

## The problem

When creating multiple leaflet maps (in a Quarto doc, or an Rmarkdown doc) with leaflegend, and I have the same group name across multiple maps, the group functionality will not work correctly within the `addLayersControl()` function. Only the last map's Layer Control will control the layer plotting, and will affect all layers across all maps. 

I am guessing this is related to Issue #25  and PR #27

## Steps to reproduce

1) Open a new quarto document, and create one code chunk.

2) Paste the following into the code chunk

```{r}
#| echo: false
#| message: false

library(leaflet)
library(leaflegend)
library(sf)
library(mapview)

dc_libraries = st_read("https://maps2.dcgis.dc.gov/dcgis/rest/services/DCGIS_DATA/Cultural_and_Society_WebMercator/MapServer/4/query?outFields=*&where=1%3D1&f=geojson")

library_map = leaflet() %>% 
  addProviderTiles("CartoDB.Positron") %>% 
  addCircles(data = dc_libraries, group = "DC Libraries")

# Make first map
library_map %>% 
  addLegendFactor(pal = colorFactor("blue", "Libraries"), 
                  shape = 'circle', 
                  opacity = 1, 
                  values = "Libraries", 
                  position = 'topright', 
                  group = 'Libraries'
                  ) %>% 
  addLayersControl(overlayGroups = c("Libraries"),
                   position = "bottomleft")

# Make second map, with same group name
library_map %>% 
  addLegendFactor(pal = colorFactor("red", "Libraries"), 
                  shape = 'circle', 
                  opacity = 1, 
                  values = "Libraries", 
                  position = 'topright', 
                  group = 'Libraries'
                  ) %>% 
  addLayersControl(overlayGroups = c("Libraries"),
                   position = "bottomleft")
```

3) Render the code chunk,  and play with the Layer Controls on map 1 and map 2. You will notice that only the Layer Control on map 2 works, and will affect the "Libraries" group in map 1. 

## Expected Behavior

Similar to Layer Controls in leaflet, layer controls should only affect the layers on the current map. And reusing layer names across different names should be supported.

**Comment by tomroh** [comment] 2024-11-28 19:30
duplicate of #78

**Closed as completed by tomroh** 2024-11-28 19:30 UTC
Labels: duplicate
